#!/usr/bin/env bash

# set this to your active development branch
develop_branch="develop"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# only check commit messages on main development branch
[ "$current_branch" != "$develop_branch" ] && exit 0

# regex to validate in commit msg
commit_regex='^(((fix|feat):+)|((M|m)erge)+)'
error_msg="Aborting commit. Your commit message format should be '<type>[optional scope]: <description>'
when 'type' is 'fix' or 'feat', or commit message: 'Merge [..]'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
