language: elixir
git:
  depth: 1000
services:
- postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - docker-ce
elixir:
- 1.6.6
otp_release:
- 20.3.8
notifications:
  slack:
    rooms:
    - secure: MAZDwNhuRd9NtHMrbVjKwjMZdAACrdKIcJwzNdORnowmYja11WruAOdtjC6N/dlIAlL1vJRlA0BXswg3M44uqt3zHXY7e3JPMfVDpLUH8b/CwdRhNK7N/CnSse7kZ5P7v8AVXk567Jm84b7fhJzGZkobRhT/R2hdPMHA/M50cOObUzY62ZEucROyvuwuDhmJYaZoUGK6X2tOpmxBtf1RQm5rVNFZWXhhtyupn/m2Hy8meTFdEdEyGoCQYtI8BCuD9Pa5XKWwZ28b38ws9ZlKV/kiDpwq0Uz1k+SKlzpo7zVZkEbdCHJF/e6JnetRmpm6i05zQdzMqc3gCC09rbZMlCoSTtcRvGZmE94YaOKd24qJK504ZJzl8PnkaUA3JXVUo4PpZqiA71sBPBe15qpnoURPMqzYKeqTHrNlhYXNBVibncl09OSSSNxBOgH0n2uqeTLS2ZXVpHUEUw6OQ8yQ6tR63qnW27xxSesewxZWvoKDOt1HLkhYAaRR4p/UOI4ae0iyUwAIBvuSH0gviqethMQ+vUWNDlI7bL7CTkiBGCApkHJPL5bPoJIE00LyuA2K7KBJsuv4ojzQ23K4zYaHTNG+7Z/nriePcJFoox1JY74apPf0VQrrPs6nxv6g6mXn9riuaU9g3jUyFwTEKUgd9FfrIHgFHZpV1jF9isByUGY=
    on_success: always
env:
  global:
  - APPS='[{"app":"api","chart":"digital-signature-api","namespace":"digital-signature","deployment":"ds-api","label":"ds-api"},{"app":"synchronizer_crl","chart":"digital-signature-api","namespace":"digital-signature","deployment":"ds-crl","label":"ds-crl"},{"app":"ocsp_service","chart":"digital-signature-api","namespace":"digital-signature","deployment":"ds-ocsp","label":"ds-ocsp"}]'
  - DOCKER_NAMESPACE=lakone
  - MIX_ENV=test
  - POSTGRES_VERSION=9.6
  - DB_PORT=5432
  - DB_NAME=ds
  - DB_PASSWORD=postgres
  - DB_USER=postgres
  - KAFKA_PORT=9092
  - DS_KAFKA_TOPIC=digital_signature
  - DS_KAFKA_PARTITIONS=10
  - KAFKA_HOST=travis
  - CONSUMER_GROUP=digital_signature
  - DB_HOST=travis
  - secure: MFfU4+uwBQQvq0n/thF95J5+JKtgkPeJPxB1Ac7/oqa8nWnD8qg/MbO3olN7Fz15YiJ8uZ3GaLYKub8ln2XALWhFdd9VAJYPiAlYkyPeWdQHqqxtHcMeoUCME+PDxjlkzDUXH9y5QVqgiFmaRALrBtqGoJaK4CQ3ep6FfwhUOSO9xSdJ/Fb861nPKMW57tnjNJDQj/1BiOVqoigpEbVFZ5YoKWb28u2ZWmWyxsgjTGCpNaKYJD/aGBws9t7FZ+WWagJhflUq7bjNvaMdeCB4ucKgvlzDDhnUssKVVJhg+JCNXruggmNT8X4gDLSZHEh+XjUz//kBnDhfwmi52RnAC9yCGHVYbc/LkAxcWnVZpPshqLj0A7wkvHJws8nqPvrwDwVy/KNfiOf/td5LQcoPX1SCeKTOiwdMp02QU5Nw7mJIXd7dZCyrBV5h/INKcSkm0fV8CwKQ4wYzASMNtrzIpVwjbUXS+qWPAS19JSJIxxE1Us3IAcUCrfsiism3eTwreQ3hD8IgAq8g+9fe4QHn2vl7mERzuWUnUbk1pgUECqjOLdkV8Z4ZaJTvsB8kNG2lZ20CkKWC0x/ABfHsi7bwYzxii5GZylsXsvtPjzQX6RQ+u8DprKZe1fDo1nfZJpITA00MuuCY9kgRdvc94zbMxrDyUD7/H3JxHV+hVI3K00s=
  - secure: j5pSXJrUNExdk1VtlWUeKvpkJrSXss9EXrZH7QejHpr22nhlep+c2cLUw4RPF498pUHJZvzdNxL236uLd2H7zXRIDH7levoTFeF1wDdGiu0hI2d3WIAcU+IIuwnPraUMmuwkQzPyUuc0grwtpGNhxReqf9k76FRwBGmHUVqTRX367+WD99YDYdYuZeLQw08eFtYmXX/14RU005aKRekUf62CzHpJizVcAso4zRSi3HyFkY3Lbb5ug5Yt6eJw0xH2l7ZL3b1ld0RV6H8eKvj2ABdldAvb9VOlsrecHKIGzD4oOhWFpxIXfpN2kEerV+8sV9C5GJWtyTiWlP666LFaNCbn4h3aqSXw9KGiiN/hzhkTJ3qlzpCoUNVlbvaiKe+cWoiVYmhbTPw2JziN12hVblzVRmP3ZK9y7JZhEQ44U3y6RZo8RjvH1GLq3V78Kbz0dCkQAgILwwgl8oAqENUJf3XwCJYNKF+kezL56MbSO9H1QCEl3aCwjVTtiNfWQOTNNVt0EAyIgqyVkNXOur36HHdfBce62nzKpUs4D3xNv22znA70BhUHBwrCHVlFMGP8SVN7DOZk0pI7BD0EHrsoRsIm7HIvuiAdA6jOkRcv6Jn5rGXE1zOPuzfmxe/a0q/CiElFiQ3iaG64TDIVEwhLhy3eBgOlvaKiDJ+JtKJo8EI=
  matrix:
  - secure: U+x32W7T3QGrOoS+cuWAqbh8Rj4I7iMAhN0FAkqvltw22PyIm110Kg0qb6C0atI7PZgBFHZC/gWty9k4hgwnqQsw2a3rQ4igpu3Dbn2ghu4dTtCgMlSXcmFKe/8lWfORsV0TAGdFyrzie70D1c+oRCiUtJZrqAiGGm40zUEZ8SmadxEXuF55eeEsLS6nRiYPaciq2tPNhriKsr4fobZ/K6T1WFq2GknkwpyTbruG741G3vYnRr7ckyGKR4xDk0sQCJMVb5XzVnCUqZYc/KQWqvXs+aNYmUHFQ221eW0R2HNfI7c776d+7flhTAfujtji4jVT31cHpgPqA6wWrE9fzq1DXYls8vYKu2Wk2pWOURKiT7KhefMwvmZ+KcBsziTfyx0ybn1U0ydYdDB4lj5gMMD9tDg5jrKYMP2t0PKjHSJvimqXzsT/MQp2Fo47Zip98WeACgq+dgzM5kZdC25v0VpkZzhMr4acFbRtYkJ+wBDbu6xZrd7bfwYg1t5iqsYvTjPWChd9ERaCuT5TSRtokNYKt9pqK45gY+ZNxLKJ+DqpfYlLVjL4eebxIHx1kwQCsOwzwa/pR1OpDbIrzfG5aTpbTOAMKaEhFntGbMODsTiCkriRTxhsgqpj/FS/vn8a1OFHbXK/UOm1627JnjYwuMNxrG83+fl1zyjUormmZjY=
  - secure: W8pQKPBhqKEEvr2HSQJoOJ8gXjrIACLlmgospAGnj2eJUw6W1vpx9g5FibMbCOJpnpTH9L1UumgbUfxDztmPFXLHanzYWpJCtjs5oeKMfvEkZuZFYk6l8hkDtmH6m2oqKFsibZrGIpIpPpoV4HUMw5zyS6EA5d7LKVnRqvxcW9RfdCU+muvyGyFTnpKEz19piT9dqPq1XIWIGEbpUKMPU65GlHEH2RIlyrdHe1Zk+YciRddzSQ8AypVLVypnMXKPP3jGdmLYVNuBKt1b3cv2bgeLPf7LMymnBUr9mGWl5TbXuspdl6zn2ggnXRm5yvSD2XkmdbQZOQKe1w9+/JkzOyCe5iE1or2gBvGcqMEFh3k3vN9xYsjF1krCOIfuBQqBxvg4X+th8RwAseDkJEu+CjHKPvYGLfOv+Dk99eu1xm+Gl5N2KoZZuVe0ihMZJib/HDMj11ngPeSVq7/abFl/CsEO5dU9j3JR71i/22hQJKyi5M/7jHXudq/mqTkdg5A8ke0852l9JbCXMaYDL5jVwGn1ZCa2RvWU6OgIIdKTZj2+GOJJyLrFemwzogtc0luirhFD4qrFeGwjO+3yh8GCGJpComjOXLmYCzV1rVDHq8PyCj4E310Nf8eEKnxKP+9qwwwL8+gW+NP4hVF1WnYwH1+z91u8MIVLL9sbuRWBx+k=
branches:
  except:
  - "/[0-9]*\\.[0-9]*\\.[0-9]*/"
before_install:
- sudo apt-get install jq
- curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/init-db.sh
  -o init-db.sh; sudo sh ./init-db.sh
- curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/init-kafka.sh
  -o init-kafka.sh; sudo sh ./init-kafka.sh
- kafka/bin/kafka-topics.sh --create --topic digital_signature --partitions $DS_KAFKA_PARTITIONS
  --replication-factor 1 --zookeeper localhost:2181
jobs:
  include:
  - stage: build and push
    name: build ocsp container
    env:
    - APPS='[{"app":"ocsp_service","chart":"digital-signature-api","namespace":"digital-signature","deployment":"ds-ocsp","label":"ds-ocsp"}]'
    script:
    - curl -s https://raw.githubusercontent.com/dhlebnikov1/ci-scripts/master/build-container.sh
      -o build-container.sh; chmod 700 ./build-container.sh
    - bash ./build-container.sh || travis_terminate 1
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - curl -s https://raw.githubusercontent.com/dhlebnikov1/ci-scripts/master/push-container.sh
      -o push-container.sh; chmod 700 ./push-container.sh
    - bash ./push-container.sh || travis_terminate 1
