FROM elixir:1.8.1  as builder

ADD . /home/ds
WORKDIR /home/ds

RUN ln -s /home/ds/apps/digital_signature/priv/libUACryptoQ.so /usr/local/lib/libUACryptoQ.so.1
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV MIX_ENV=test

# RUN TESTS #
# Database settings
ENV DB_HOST=travis
ENV DB_NAME=ds
ENV DB_USER=postgres
ENV DB_PASSWORD=postgres
ENV DB_PORT=5432
ENV DB_POOL_SIZE=5
ENV EHEALTH_EMAIL_ENDPOINT=http://127.0.0.1

#kafka
ENV KAFKA_BROKERS=travis:9092
ENV DS_KAFKA_PARTITIONS=10
ENV DS_KAFKA_TOPIC=digital_signature
ENV CONSUMER_GROUP=digital_signature

ENV REPLACE_OS_VARS=true

RUN mix do \
  local.hex --force, \
  local.rebar --force, \
  deps.get, \
  test --exclude pending --trace
